src/Controllers/AdjVoucherController.cs
using AD_Project.DbContext;
using AD_Project.Models.Store;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace AD_Project.Controllers
{
    [Authorize(Roles = "1")]
    public class AdjVoucherController : Controller
    {
        ApplicationDbContext Db = new ApplicationDbContext();
        // GET: AdjVoucher
        public ActionResult create()
        {

            return View();
        }


        [HttpPost]
        public ActionResult save(AdjustedItem adj,FormCollection form)
        {
            int ItemIdInForm = int.Parse(form["ItemId"]);
            var reqs = Db.Items.SingleOrDefault(i => i.Id == ItemIdInForm);
            if (reqs == null)
            {
                Item item = new Item();
                adj.Item = item;
                Db.AdjustedItems.Add(adj);
                Db.SaveChanges();

            }
            else
            {
                adj.ItemId = int.Parse(form["ItemId"]);
                adj.status = "Pending";
                Db.AdjustedItems.Add(adj);
                Db.SaveChanges();
            }

            return RedirectToAction("Home", "Adjvoucher");
        }

        public ActionResult Home()
        {

            var voucher = Db.AdjustedItems.Include(i => i.Item).Where(h => h.status=="Pending").ToList();
            return View(voucher);
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var voucher = Db.AdjustedItems.Include(i => i.Item).SingleOrDefault(i => i.AdjustedItemId == id);
            return View(voucher);
        }


        [HttpPost]
        public ActionResult Edit(AdjustedItem productObj)
        {
            var product = Db.AdjustedItems.Include(i => i.Item).SingleOrDefault(i => i.AdjustedItemId == productObj.AdjustedItemId);

            product.Item.ItemNumber = productObj.Item.ItemNumber;
            product.AdjustedQty = productObj.AdjustedQty;
            product.AdjustmentReason = productObj.AdjustmentReason;
            Db.SaveChanges();
            return RedirectToAction("Home");
        }

        public ActionResult Delete(int id)
        {
            var product = Db.AdjustedItems.Include(i => i.Item).Where(i => i.AdjustedItemId == id).FirstOrDefault();
            Db.AdjustedItems.Remove(product);
            Db.SaveChanges();
            return RedirectToAction("Home");
        }

       /* public ActionResult AdjToSupervisor()
        {
            var voucher = Db.AdjustedItems.Include(i => i.Item).ToList();
            return View(voucher);

        }*/


    }
}

src/Controllers/ClerkController.cs
using AD_Project.DbContext;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using AD_Project.ViewModel;
using System.Diagnostics;
using AD_Project.Models.Store;
using AD_Project.Models.Departments;
using AD_Project.Services;
using System.Net.Mail;
using System.Net;
using System.Text;

namespace AD_Project.Controllers
{
    [Authorize(Roles = "1")]
    public class ClerkController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
       
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult DisplayRequestedItems()
        {
            var reqs = db.ConsolidatedRequisitions.Include(c => c.Department).Where(h => h.ConsolidatedRequisitionStatus == "Approved").ToList();
            return View(reqs);
        }
        public ActionResult RequestOfEachDept(int id)
        {
            var requestedDeptDetails = db.ConsolidatedRequisitions.Include(i => i.CollectionOfReq.Select(it => it.Item))
                .SingleOrDefault(m => m.ConsolidatedRequisitionId == id);

            return View(requestedDeptDetails);
        }

        public ActionResult RetrievalForm()
        {
            DisplayRetrievalForm dis = new DisplayRetrievalForm();
            return View(dis.DisplayRetrieval());
        }

        //Saif

        public ActionResult DisburmentList()
        {
            List<Department> departments = db.Departments.ToList();

            var disbursementViewModel = new DisbursementViewModel();
            disbursementViewModel.DisbursementList = new DisbursementList();
            disbursementViewModel.DisbursementList.DisburseItems = new List<DisburseItem>();
            disbursementViewModel.Departments = departments;

            return View(disbursementViewModel);
        }

        public ActionResult DisplayDisburmentList(DisbursementViewModel disbursementViewModel)
        {
            List<Department> departments = db.Departments.ToList();
            disbursementViewModel.DisbursementList = new DisbursementList();
            disbursementViewModel.DisbursementList.DisburseItems = new List<DisburseItem>();
            var disburmentList = db.DisbursementLists.Include(m => m.DisburseItems
            .Select(a => a.Item))
            .FirstOrDefault(m => m.Department.DeptId == disbursementViewModel.SelectedDepId && m.Status == "pending");


            try
            {
                if (disburmentList.DisburseItems.Count != 0)
                {
                    if (disburmentList.Status == "pending")
                    {
                        disbursementViewModel.DisbursementList = disburmentList;
                    }
                }
                disbursementViewModel.Departments = departments;
                if (disburmentList != null)
                {
                    return View("DisburmentList", disbursementViewModel);
                }
                else
                {
                    return RedirectToAction("DisburmentList");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return RedirectToAction("DisburmentList");
            }
        }

        [HttpPost]
        public ActionResult UpdateRetrievalList(RetrievalFormViewModel retrievalFormViewModel)
        {
           
            List<DeptRequestedItems> DeptList;
            DisplayRetrievalForm dis = new DisplayRetrievalForm();
            RetrievalFormViewModel ret = dis.DisplayRetrieval();
            DeptList = ret.deptRequestedItems;
            UpdateDisbursementList d = new UpdateDisbursementList();
            d.UpdateDisbursement(DeptList, retrievalFormViewModel);

          /*  var deptActual = db.DeptRequestedItems.ToList();
            foreach(var g in deptActual)
            {
                RetrievalList retrievalList = new RetrievalList();
                retrievalList.DeptId = g.DeptId;
                retrievalList.ItemId = g.itemId;
                retrievalList.RequestedQty = g.DeptRequestedQtyForEachItem;
                string str = "ActualQty" + g.itemId + g.DeptId;
                retrievalList.ActualQty = Convert.ToInt32(form["str"]);
                db.RetrievalLists.Add(retrievalList);
            }*/
            db.SaveChanges();           
            return RedirectToAction("DisburmentList");

        }

    }
}

src/Controllers/SupplierController.cs
using AD_Project.DbContext;
using AD_Project.Models.Store;

using AD_Project.ViewModel;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace AD_Project.Controllers
{
    [Authorize(Roles = "1")]
    public class SupplierController : Controller
    {
        private ApplicationDbContext _context;

        public SupplierController()
        {
            _context = new ApplicationDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        /*public ActionResult PurchaseOrder()
        {

            var ItemsSupplier = _context.Items.Include(c => c.Stockdetails).Include(c => c.Suppliers_Prices).ToList();


            List<Item> it = new List<Item>();
            foreach (var x in ItemsSupplier)
            {
                foreach (var j in x.Stockdetails)
                {
                    foreach (var q in x.Suppliers_Prices)
                    {
                        if (j.InventoryStockQty < x.ReorderLevel && j.ItemId == x.Id)
                        {
                            it.Add(x);

                        }
                    }

                }
            }

            return View(it);

        }*/

        public ActionResult PurchaseOrder()
        {
            List<Item> items = _context.Items.ToList();
            List<Supplier> suppliers = _context.Suppliers.ToList();
            List<Suppliers_Price> suppliers_Price = _context.Suppliers_Prices.ToList();

            var PurchaseOrderViewModel = new PurchaseOrderViewModel();
            PurchaseOrderViewModel.Items = items;
            PurchaseOrderViewModel.Suppliers = suppliers;
            PurchaseOrderViewModel.SuppliersPrice = suppliers_Price;


            return View(PurchaseOrderViewModel);
        }

        public ActionResult SpecifySupplier(PurchaseOrderViewModel purchaseOrderViewModel)
        {
            List<Item> items = _context.Items.ToList();
            List<Supplier> suppliers = _context.Suppliers.ToList();
            List<Suppliers_Price> suppliers_Prices = _context.Suppliers_Prices.ToList();


           /* var ItemsSupplier = _context.Items.Include(c => c.Suppliers_Prices).Include(c => c.Stockdetails)
                .SingleOrDefault(m => m.SupplierPriceId == purchaseOrderViewModel.SelectedsupplierId);*/

            var itemsOfSupplier = _context.Suppliers_Prices.Include(d => d.Item).Include(g => g.Supplier)
                .Where(f => f.SupplierId == purchaseOrderViewModel.SelectedsupplierId);

            try
            {
               // purchaseOrderViewModel.iitems = items;

                purchaseOrderViewModel.SuppliersPrice = itemsOfSupplier;
                purchaseOrderViewModel.Suppliers = suppliers;
                purchaseOrderViewModel.Items = items;

                return View("PurchaseOrder", purchaseOrderViewModel);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return RedirectToAction("DisburmentList");
            }

        }

        public ViewResult Low_Stock()
        {
            List<Item> item = new List<Item>();
            var low = _context.Items.Include(c => c.Stockdetails).ToList();

            foreach (var i in low)
            {
                foreach (var j in i.Stockdetails)
                {
                    if (j.InventoryStockQty < i.ReorderLevel)
                    {
                        item.Add(i);
                    }
                }
            }
            return View(item);
        }
        public ActionResult Generate()
        {
            var supplierName = _context.Suppliers.ToList();
            var viewModel = new PurchaseOrderViewModel
            {
                Suppliers = supplierName
            };
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Create(FormCollection f)
        {
            /*var ds = f["suppliers"];
            if(ds == "BANE")
            {

            }*/
            return View();
        }
    }
}

src/Views/Shared/_ClerkLayout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/assets/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="~/Content/assets/css/style.css" rel="stylesheet" />
    <link href="~/Content/assets/js/gritter/css/jquery.gritter.css" rel="stylesheet" />
    <link href="~/Content/assets/lineicons/style.css" rel="stylesheet" />
    <link href="~/Content/assets/css/style-responsive.css" rel="stylesheet" />
    <script src="~/Content/assets/js/chart-master/Chart.js"></script>

    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <section id="container">
        <header class="header black-bg">
            <div class="sidebar-toggle-box">
                <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
            </div>
            <a onclick="location.href='@Url.Action("DisplayRequestedItems", "Clerk")'" class="logo"><b>SSIS</b></a>
            <div class="top-menu">
                <ul class="nav pull-right top-menu">
                    <li><a class="logout" onclick="location.href='@Url.Action("Login", "Account")'">Logout</a></li>
                </ul>
            </div>
        </header>
        <aside>
            <div id="sidebar" class="nav-collapse ">
                <!-- sidebar menu start-->
                <ul class="sidebar-menu" id="nav-accordion">
                    <li class="centered"><img src="~/Content/assets/img/ui-sam.jpg" class="img-circle" width="60"></li>
                    <li class="centered"><span style="color:white;"><strong>Hello,@User.Identity.GetUserName()!</strong></span></li>
                    <li class="sub-menu">
                        <a href="javascript:;" onclick="location.href='@Url.Action("DisplayRequestedItems", "Clerk")'">
                            <i class="fa fa-desktop"></i>
                            <span>Request Details</span>
                        </a>
                    </li>
                    <li class="sub-menu">
                        <a href="javascript:;" onclick="location.href='@Url.Action("RetrievalForm", "Clerk")'">
                            <i class="fa fa-cogs"></i>
                            <span>Retrieval Form</span>
                        </a>
                    </li>
                    <li class="sub-menu">
                        <a href="javascript:;" onclick="location.href='@Url.Action("DisburmentList", "Clerk")'">
                            <i class="fa fa-book"></i>
                            <span>Disbursement List</span>
                        </a>
                    </li>
                    <li class="sub-menu">
                        <a href="javascript:;" onclick="location.href='@Url.Action("Home", "AdjVoucher")'">
                            <i class="fa fa-tasks"></i>
                            <span>Adjustment Voucher</span>
                        </a>
                    </li>
                    <li class="sub-menu">
                        <a href="javascript:;" onclick="location.href='@Url.Action("Low_Stock", "Supplier")'">
                            <i class=" fa fa-bar-chart-o"></i>
                            <span>Low-Stock Items</span>
                        </a>
                    </li>
                    <li class="sub-menu">
                        <a href="javascript:;" onclick="location.href='@Url.Action("PurchaseOrder", "Supplier")'">
                            <i class="fa fa-th"></i>
                            <span>Purchase Order</span>
                        </a>
                    </li>

                </ul>
                <!-- sidebar menu end-->
            </div>
        </aside>
        <!--sidebar end-->


        <section id="main-content">
            <section class="wrapper">

                @RenderBody()

            </section>
        </section>
    </section>
    <script src="~/Content/assets/js/jquery.js"></script>
    <script src="~/Content/assets/js/jquery-1.8.3.min.js"></script>
    <script src="~/Content/assets/js/jquery.dcjqaccordion.2.7.js"></script>
    <script src="~/Content/assets/js/bootstrap.min.js"></script>
    <script src="~/Content/assets/js/jquery.scrollTo.min.js"></script>
    <script src="~/Content/assets/js/jquery.nicescroll.js"></script>
    <script src="~/Content/assets/js/jquery.sparkline.js"></script>
    <script src="~/Content/assets/js/common-scripts.js"></script>
    <script src="~/Content/assets/js/gritter/js/jquery.gritter.js"></script>
    <script src="~/Content/assets/js/gritter-conf.js"></script>
    <script>
        $(document).ready(function () {
            $("#date-popover").popover({ html: true, trigger: "manual" });
            $("#date-popover").hide();
            $("#date-popover").click(function (e) {
                $(this).hide();
            });

            $("#my-calendar").zabuto_calendar({
                action: function () {
                    return myDateFunction(this.id, false);
                },
                action_nav: function () {
                    return myNavFunction(this.id);
                },
                ajax: {
                    url: "show_data.php?action=1",
                    modal: true
                },
                legend: [
                    { type: "text", label: "Special event", badge: "00" },
                    { type: "block", label: "Regular event", }
                ]
            });
        });


        function myNavFunction(id) {
            $("#date-popover").hide();
            var nav = $("#" + id).data("navigation");
            var to = $("#" + id).data("to");
            console.log('nav ' + nav + ' to: ' + to.month + '/' + to.year);
        }
    </script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

src/Views/Shared/_EmpLayout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/assets/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="~/Content/assets/css/style.css" rel="stylesheet" />
    <link href="~/Content/assets/js/gritter/css/jquery.gritter.css" rel="stylesheet" />
    <link href="~/Content/assets/lineicons/style.css" rel="stylesheet" />
    <link href="~/Content/assets/css/style-responsive.css" rel="stylesheet" />
    <script src="~/Content/assets/js/chart-master/Chart.js"></script>
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <section id="container">
        <header class="header black-bg">
            <div class="sidebar-toggle-box">
                <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
            </div>
            <a onclick="location.href='@Url.Action("Catalogue", "Employee")'" class="logo"><b>SSIS</b></a>
            <div class="top-menu">
                <ul class="nav pull-right top-menu">
                    <li><a class="logout" onclick="location.href='@Url.Action("Login", "Account")'">Logout</a></li>
                </ul>
            </div>
        </header>
        <aside>
            <div id="sidebar" class="nav-collapse ">
                <!-- sidebar menu start-->
                <ul class="sidebar-menu" id="nav-accordion">
                    <li class="centered"><img src="~/Content/assets/img/ui-sam.jpg" class="img-circle" width="60"></li>
                    <li class="centered"><span style="color:white;"><strong>Hello,@User.Identity.GetUserName().Remove(0,4)!</strong></span></li>
                    <li class="sub-menu">
                        <a href="javascript:;" onclick="location.href='@Url.Action("Catalogue", "Employee")'">
                            <i class="fa fa-desktop"></i>
                            <span>Catalogue</span>
                        </a>
                    </li>
                    @if (User.IsInRole("7"))
                    {
                        <li class="sub-menu">
                            <a href="javascript:;" onclick="location.href='@Url.Action("PendingForApproval", "Employee")'">
                                <i class="fa fa-cogs"></i>
                                <span>Interim</span>
                            </a>
                        </li>
                    }
                </ul>
                <!-- sidebar menu end-->
            </div>
        </aside>
        <!--sidebar end-->


        <section id="main-content">
            <section class="wrapper">

                @RenderBody()
               
            </section>
        </section>
    </section>
    <script src="~/Content/assets/js/jquery.js"></script>
    <script src="~/Content/assets/js/jquery-1.8.3.min.js"></script>
    <script src="~/Content/assets/js/jquery.dcjqaccordion.2.7.js"></script>
    <script src="~/Content/assets/js/bootstrap.min.js"></script>
    <script src="~/Content/assets/js/jquery.scrollTo.min.js"></script>
    <script src="~/Content/assets/js/jquery.nicescroll.js"></script>
    <script src="~/Content/assets/js/jquery.sparkline.js"></script>
    <script src="~/Content/assets/js/common-scripts.js"></script>
    <script src="~/Content/assets/js/gritter/js/jquery.gritter.js"></script>
    <script src="~/Content/assets/js/gritter-conf.js"></script>
    <script>
        $(document).ready(function () {
            $("#date-popover").popover({ html: true, trigger: "manual" });
            $("#date-popover").hide();
            $("#date-popover").click(function (e) {
                $(this).hide();
            });

            $("#my-calendar").zabuto_calendar({
                action: function () {
                    return myDateFunction(this.id, false);
                },
                action_nav: function () {
                    return myNavFunction(this.id);
                },
                ajax: {
                    url: "show_data.php?action=1",
                    modal: true
                },
                legend: [
                    { type: "text", label: "Special event", badge: "00" },
                    { type: "block", label: "Regular event", }
                ]
            });
        });


        function myNavFunction(id) {
            $("#date-popover").hide();
            var nav = $("#" + id).data("navigation");
            var to = $("#" + id).data("to");
            console.log('nav ' + nav + ' to: ' + to.month + '/' + to.year);
        }
    </script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

   
</body>
</html>

src/Views/Shared/_HeadLayout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/assets/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="~/Content/assets/css/style.css" rel="stylesheet" />
    <link href="~/Content/assets/js/gritter/css/jquery.gritter.css" rel="stylesheet" />
    <link href="~/Content/assets/lineicons/style.css" rel="stylesheet" />
    <link href="~/Content/assets/css/style-responsive.css" rel="stylesheet" />
    <script src="~/Content/assets/js/chart-master/Chart.js"></script>
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <section id="container">
        <header class="header black-bg">
            <div class="sidebar-toggle-box">
                <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
            </div>
            <a onclick="location.href='@Url.Action("PendingForApproval", "Head")'" class="logo"><b>SSIS</b></a>
            <div class="top-menu">
                <ul class="nav pull-right top-menu">
                    <li><a class="logout" onclick="location.href='@Url.Action("Login", "Account")'">Logout</a></li>
                </ul>
            </div>
        </header>
        <aside>
            <div id="sidebar" class="nav-collapse ">
                <!-- sidebar menu start-->
                <ul class="sidebar-menu" id="nav-accordion">
                    <li class="centered"><img src="~/Content/assets/img/ui-sam.jpg" class="img-circle" width="60"></li>
                    <li class="centered"><span style="color:white;"><strong>Hello,@User.Identity.GetUserName().Remove(0, 4)!</strong></span></li>
                    <li class="sub-menu">
                        <a href="javascript:;" onclick="location.href='@Url.Action("PendingForApproval", "Head")'">
                            <i class="fa fa-desktop"></i>
                            <span>PendingForApproval</span>
                        </a>
                    </li>
                    <li class="sub-menu">
                        <a href="javascript:;" onclick="location.href='@Url.Action("AssignDelegate", "Head")'">
                            <i class=" fa fa-bar-chart-o"></i>
                            <span>Delegate Authority</span>
                        </a>
                    </li>
                    <li class="sub-menu">
                        <a href="javascript:;" onclick="location.href='@Url.Action("AssignRep", "Head")'">
                            <i class=" fa fa-bar-chart-o"></i>
                            <span>Assign Representative</span>
                        </a>
                    </li>

                </ul>
                <!-- sidebar menu end-->
            </div>
        </aside>
        <!--sidebar end-->


        <section id="main-content">
            <section class="wrapper">

                @RenderBody()

            </section>
        </section>
    </section>
    <script src="~/Content/assets/js/jquery.js"></script>
    <script src="~/Content/assets/js/jquery-1.8.3.min.js"></script>
    <script src="~/Content/assets/js/jquery.dcjqaccordion.2.7.js"></script>
    <script src="~/Content/assets/js/bootstrap.min.js"></script>
    <script src="~/Content/assets/js/jquery.scrollTo.min.js"></script>
    <script src="~/Content/assets/js/jquery.nicescroll.js"></script>
    <script src="~/Content/assets/js/jquery.sparkline.js"></script>
    <script src="~/Content/assets/js/common-scripts.js"></script>
    <script src="~/Content/assets/js/gritter/js/jquery.gritter.js"></script>
    <script src="~/Content/assets/js/gritter-conf.js"></script>
    <script>
        $(document).ready(function () {
            $("#date-popover").popover({ html: true, trigger: "manual" });
            $("#date-popover").hide();
            $("#date-popover").click(function (e) {
                $(this).hide();
            });

            $("#my-calendar").zabuto_calendar({
                action: function () {
                    return myDateFunction(this.id, false);
                },
                action_nav: function () {
                    return myNavFunction(this.id);
                },
                ajax: {
                    url: "show_data.php?action=1",
                    modal: true
                },
                legend: [
                    { type: "text", label: "Special event", badge: "00" },
                    { type: "block", label: "Regular event", }
                ]
            });
        });


        function myNavFunction(id) {
            $("#date-popover").hide();
            var nav = $("#" + id).data("navigation");
            var to = $("#" + id).data("to");
            console.log('nav ' + nav + ' to: ' + to.month + '/' + to.year);
        }
    </script>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

src/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
  
    @*<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>*@
    <div class="container body-content">
        @RenderBody()

    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>